import { useMutation } from "@tanstack/react-query";
import { CheckCircle2, Equal, Play, Scale, XCircle } from "lucide-react";
import { api } from "../../api";
import { Button, EmptyState, PageHeader, Panel, StatusPill, useToast } from "../../components/ui";
import { formatMoney, shortId } from "../../utils";

export function ReconciliationPage() {
  const toast = useToast();
  const mutation = useMutation({ mutationFn: api.runReconciliation, onSuccess: (run) => toast.success(`Reconciliation ${run.status.toLowerCase()}`, `${run.accounts_checked} accounts checked.`), onError: (error) => toast.error("Reconciliation failed", error) });
  const run = mutation.data;
  return <div className="page-stack"><PageHeader eyebrow="Ledger controls" title="Balance reconciliation" description="Compare every projected account balance with the authoritative sum of immutable ledger entries." action={<Button onClick={() => mutation.mutate()} disabled={mutation.isPending}><Play size={16} /> {mutation.isPending ? "Running control…" : "Run reconciliation"}</Button>} /><div className="recon-explainer"><span><Scale size={22} /></span><div><strong>Control equation</strong><p>account_balances.current_balance_minor</p></div><Equal size={20} /><div><strong>Ledger truth</strong><p>SUM(ledger_entries.amount_minor)</p></div></div>{!run ? <Panel><EmptyState title="No reconciliation run yet" description="Run the control to compare projections against the ledger." /></Panel> : <><div className="metric-grid recon-metrics"><Panel className={`metric-card metric-${run.status === "PASS" ? "positive" : "warning"}`}><div className="metric-card-head"><span>Overall result</span>{run.status === "PASS" ? <CheckCircle2 /> : <XCircle />}</div><strong>{run.status}</strong><small>{run.status === "PASS" ? "All projections match" : "Investigation required"}</small></Panel><Panel className="metric-card"><div className="metric-card-head"><span>Accounts checked</span><Scale /></div><strong>{run.accounts_checked}</strong><small>System and customer accounts</small></Panel><Panel className="metric-card"><div className="metric-card-head"><span>Mismatches</span><XCircle /></div><strong>{run.mismatches}</strong><small>Projection differences</small></Panel></div><Panel padded={false}><div className="panel-heading panel-heading-padded"><div><p className="eyebrow">Control results</p><h2>Account comparison</h2></div><StatusPill value={run.status} /></div><div className="table-wrap"><table><thead><tr><th>Account</th><th>Projected balance</th><th>Ledger balance</th><th>Result</th></tr></thead><tbody>{run.results.map((result) => <tr key={result.account_id}><td><code>{shortId(result.account_id)}</code></td><td>{formatMoney(result.projected_balance_minor)}</td><td>{formatMoney(result.authoritative_balance_minor)}</td><td><StatusPill value={result.matches ? "PASS" : "FAIL"} /></td></tr>)}</tbody></table></div></Panel></>}</div>;
}
