server_name: "bantam-nats"
listen: "0.0.0.0:4222"
http: "0.0.0.0:8222"

authorization {
  user: $NATS_BANTAM_USER
  password: $NATS_BANTAM_PASSWORD
  timeout: 2
}

tls {
  cert_file: "/run/tls/nats.crt"
  key_file: "/run/tls/nats.key"
  ca_file: "/run/tls/ca.crt"
  min_version: "1.2"
  timeout: 2
}

jetstream {
  store_dir: "/data"
  key: $NATS_JETSTREAM_KEY
  max_file_store: 1G
}
