#!/bin/sh

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
compose_file="$script_dir/compose.yml"
env_file="$script_dir/production.env"
runtime_dir="$script_dir/runtime"
tls_dir="$runtime_dir/tls"

usage() {
    echo "usage:" >&2
    echo "  $0 bantam.example.com operator@example.com [super-admin@example.com]" >&2
    echo "  $0 --rotate-certs" >&2
    echo "  $0 --rotate-ca" >&2
    exit 2
}

mode=initialize
case "${1:-}" in
    --rotate-certs|--rotate-ca)
        [ "$#" -eq 1 ] || usage
        mode=${1#--}
        ;;
    *)
        [ "$#" -ge 2 ] && [ "$#" -le 3 ] || usage
        deploy_domain=$1
        acme_email=$2
        super_admin_email=${3:-${BANTAM_SUPER_ADMIN_EMAIL:-}}
        ;;
esac

for command_name in docker openssl grep; do
    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "$command_name is required" >&2
        exit 1
    fi
done
if ! docker compose version >/dev/null 2>&1; then
    echo "the Docker Compose plugin is required" >&2
    exit 1
fi

if [ "$mode" = initialize ]; then
    if ! printf '%s\n' "$deploy_domain" | grep -Eq \
        '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'; then
        echo "domain must be a lowercase DNS hostname such as bantam.example.com" >&2
        exit 2
    fi
    case "$acme_email" in
        *@*.*) ;;
        *)
            echo "ACME email must look like operator@example.com" >&2
            exit 2
            ;;
    esac
    if printf '%s' "$acme_email" | grep -q '[[:space:]]'; then
        echo "ACME email cannot contain whitespace" >&2
        exit 2
    fi
    if [ -n "$super_admin_email" ]; then
        case "$super_admin_email" in
            *@*.*) ;;
            *)
                echo "super admin email must look like admin@example.com" >&2
                exit 2
                ;;
        esac
        if printf '%s' "$super_admin_email" | grep -q '[[:space:]]'; then
            echo "super admin email cannot contain whitespace" >&2
            exit 2
        fi
        super_admin_email=$(printf '%s' "$super_admin_email" | tr '[:upper:]' '[:lower:]')
    fi
    if [ -e "$env_file" ] || [ -e "$tls_dir" ]; then
        echo "production.env or runtime/tls already exists; refusing to rotate deployment secrets implicitly" >&2
        echo "use --rotate-certs or --rotate-ca for an existing deployment" >&2
        exit 1
    fi
else
    if [ ! -f "$env_file" ] || [ ! -d "$tls_dir" ]; then
        echo "an existing production.env and runtime/tls are required for certificate rotation" >&2
        exit 1
    fi
    if [ ! -f "$tls_dir/ca/ca.crt" ]; then
        echo "the current internal CA certificate is missing" >&2
        exit 1
    fi
    if [ "$mode" = rotate-certs ] && [ ! -f "$tls_dir/ca/ca.key" ]; then
        echo "the current internal CA private key is required for leaf rotation" >&2
        echo "run $0 --rotate-ca to replace the trust root instead" >&2
        exit 1
    fi
fi

umask 077
staging_dir=$(mktemp -d "$script_dir/.prepare.XXXXXX")
env_staging="$staging_dir/production.env"
tls_staging="$staging_dir/tls"
trap 'rm -rf "$staging_dir"' EXIT HUP INT TERM

mkdir -p \
    "$tls_staging/ca" \
    "$tls_staging/client" \
    "$tls_staging/postgres" \
    "$tls_staging/nats"

create_ca() {
    openssl genrsa -out "$tls_staging/ca/ca.key" 3072 >/dev/null 2>&1
    openssl req -x509 -new -sha256 -days 3650 \
        -key "$tls_staging/ca/ca.key" \
        -subj "/CN=Bantam Droplet Internal CA" \
        -out "$tls_staging/ca/ca.crt"
}

if [ "$mode" = initialize ]; then
    postgres_password="p$(openssl rand -hex 32)"
    nats_password="n$(openssl rand -hex 32)"
    nats_jetstream_key="j$(openssl rand -hex 32)"
    jwt_secret="$(openssl rand -hex 48)"
    sca_secret="$(openssl rand -hex 48)"
    claims_secret="$(openssl rand -hex 48)"
    mfa_encryption_key=$(openssl rand -base64 32 | tr '/+' '_-' | tr -d '\n')

    cat >"$env_staging" <<EOF
# Generated by deploy/digitalocean/prepare.sh. Keep this file mode 0600,
# outside version control, and in the same encrypted backup as the database.
BANTAM_DOMAIN=$deploy_domain
ACME_EMAIL=$acme_email
BANTAM_IMAGE_TAG=local
BANTAM_API_IMAGE=bantam-api:local
BANTAM_WEB_IMAGE=bantam-web:local

POSTGRES_PASSWORD=$postgres_password
NATS_PASSWORD=$nats_password
NATS_JETSTREAM_KEY=$nats_jetstream_key
JWT_SECRET=$jwt_secret
SCA_SECRET=$sca_secret
CLAIMS_SECRET=$claims_secret
MFA_ENCRYPTION_KEY=$mfa_encryption_key

# Optional. Matching BANK_ADMIN email is treated as the super admin.
BANTAM_SUPER_ADMIN_EMAIL=$super_admin_email

# Optional server-side credentials. Leave blank to disable the integration.
ASPIS_MISTRAL_API_KEY=
WORKFLOW_GITHUB_TOKEN=
EOF
    create_ca
elif [ "$mode" = rotate-ca ]; then
    create_ca
else
    # Leaf rotation preserves the deployed trust root and signing key.
    cp "$tls_dir/ca/ca.crt" "$tls_staging/ca/ca.crt"
    cp "$tls_dir/ca/ca.key" "$tls_staging/ca/ca.key"
    if [ -f "$tls_dir/ca/ca.srl" ]; then
        cp "$tls_dir/ca/ca.srl" "$tls_staging/ca/ca.srl"
    fi
    if ! openssl x509 -checkend 77760000 -noout \
        -in "$tls_staging/ca/ca.crt" >/dev/null; then
        echo "the internal CA expires too soon for a new 825-day leaf certificate" >&2
        echo "run $0 --rotate-ca instead" >&2
        exit 1
    fi
fi

issue_server_certificate() {
    service_name=$1
    service_dir="$tls_staging/$service_name"
    extension_file="$staging_dir/$service_name.ext"

    openssl genrsa -out "$service_dir/$service_name.key" 3072 >/dev/null 2>&1
    openssl req -new -sha256 \
        -key "$service_dir/$service_name.key" \
        -subj "/CN=$service_name" \
        -out "$staging_dir/$service_name.csr"
    cat >"$extension_file" <<EOF
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth
subjectAltName=DNS:$service_name
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer
EOF
    openssl x509 -req -sha256 -days 825 \
        -in "$staging_dir/$service_name.csr" \
        -CA "$tls_staging/ca/ca.crt" \
        -CAkey "$tls_staging/ca/ca.key" \
        -CAserial "$tls_staging/ca/ca.srl" \
        -CAcreateserial \
        -extfile "$extension_file" \
        -out "$service_dir/$service_name.crt" >/dev/null 2>&1
    cp "$tls_staging/ca/ca.crt" "$service_dir/ca.crt"
}

issue_server_certificate postgres
issue_server_certificate nats

cp "$tls_staging/ca/ca.crt" "$tls_staging/client/ca.crt"
docker run --rm --entrypoint cat python:3.13-slim-bookworm \
    /etc/ssl/certs/ca-certificates.crt >"$tls_staging/client/ca-bundle.crt"
cat "$tls_staging/ca/ca.crt" >>"$tls_staging/client/ca-bundle.crt"

openssl verify -CAfile "$tls_staging/ca/ca.crt" \
    "$tls_staging/postgres/postgres.crt" \
    "$tls_staging/nats/nats.crt" >/dev/null

chmod 0700 "$tls_staging/ca"
chmod 0755 "$tls_staging/client" "$tls_staging/postgres" "$tls_staging/nats"
chmod 0600 \
    "$tls_staging/ca/ca.key" \
    "$tls_staging/postgres/postgres.key" \
    "$tls_staging/nats/nats.key"
chmod 0644 \
    "$tls_staging/ca/ca.crt" \
    "$tls_staging/client/ca.crt" \
    "$tls_staging/client/ca-bundle.crt" \
    "$tls_staging/postgres/ca.crt" \
    "$tls_staging/postgres/postgres.crt" \
    "$tls_staging/nats/ca.crt" \
    "$tls_staging/nats/nats.crt"

# postgres:16-alpine runs the server as UID/GID 70. The helper changes only
# the staged server key; the CA signing key remains root-only and is never
# mounted into a runtime service.
docker run --rm --user 0:0 --entrypoint sh \
    -v "$tls_staging/postgres:/tls" \
    postgres:16-alpine \
    -c 'chown 70:70 /tls/postgres.key && chmod 0600 /tls/postgres.key'

if [ "$mode" = initialize ]; then
    docker compose --env-file "$env_staging" -f "$compose_file" config --quiet
    mkdir -p "$runtime_dir"
    chmod 0700 "$runtime_dir"
    mv "$tls_staging" "$tls_dir"
    mv "$env_staging" "$env_file"
    chmod 0600 "$env_file"

    echo "Prepared Bantam production configuration for https://$deploy_domain"
    echo "Next: add optional Mistral/GitHub keys to $env_file, then follow README.md"
    exit 0
fi

docker compose --env-file "$env_file" -f "$compose_file" config --quiet
rotation_id="$(date -u +%Y%m%dT%H%M%SZ)-$$"
previous_tls_dir="$runtime_dir/tls.previous.$rotation_id"
if [ -e "$previous_tls_dir" ]; then
    echo "rotation backup already exists: $previous_tls_dir" >&2
    exit 1
fi
mv "$tls_dir" "$previous_tls_dir"
if ! mv "$tls_staging" "$tls_dir"; then
    mv "$previous_tls_dir" "$tls_dir"
    echo "certificate rotation failed; the previous directory was restored" >&2
    exit 1
fi

echo "Installed $mode material; previous certificates remain at $previous_tls_dir"
echo "Recreate the stack now so every service switches trust material together:"
echo "docker compose --env-file $env_file -f $compose_file up -d --force-recreate"
