"""Refresh the curated attack trees with Mistral, from a trusted environment.

GitHub Pages cannot hold a secret, so this is the supported way to put a Mistral
key behind the published trees: run it where a secret is safe - a GitHub Actions
job reading a repository secret, or a maintainer's machine - and commit the
reviewed result.  The key never reaches the published artifact.

The output is validated exactly as the report build validates it, so a run that
produces an ungrounded tree fails here rather than shipping.

    ASPIS_MISTRAL_API_KEY=... python -m scripts.generate_attack_trees \
        --output report/attack-trees.json
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

from bantam.repository_graph import MistralClient, ModelRequestError
from bantam.workflow_graph import load_catalog
from scripts.attack_tree_library import (
    AttackTreeLibraryError,
    LIBRARY_VERSION,
    PROMPT_LIMITS,
    parse_tree_set,
    request_descriptor,
    validate_library,
)
from scripts.resilience_report import (
    _read_mapping,
    build_public_projection,
    collect_repository_evidence,
)


GENERATED_NOTE = (
    "Attack trees generated by Mistral from Bantam's deterministic graph and "
    "validated against it. Regenerate with scripts.generate_attack_trees; review "
    "the wording before committing, because a model wrote it."
)


def reduce_projection(
    projection: dict[str, Any], limits: dict[str, int] | None = None
) -> dict[str, Any]:
    """Cut the published projection down to a promptable size.

    This mirrors the reduction the report page performs in the browser, so a
    tree generated here and a tree a reader generates are built from the same
    view of the bank.
    """

    caps = limits or PROMPT_LIMITS
    by_id = {node["id"]: node for node in projection["nodes"]}
    flows = projection["flows"][: caps["max_flows"]]
    selected: list[str] = []
    seen: set[str] = set()
    for flow in flows:
        for node_id in flow["node_ids"]:
            if node_id not in seen and len(selected) < caps["max_nodes"]:
                seen.add(node_id)
                selected.append(node_id)
    reduced = {
        "repository": projection["repository"],
        "graph_digest": projection["catalogue_digest"],
        "counts": projection["catalogue_counts"],
        "complete": len(seen) == len(projection["nodes"])
        and len(flows) == len(projection["flows"]),
        "flows": [
            {
                "flow_id": flow["id"],
                "name": flow["name"],
                "actor_roles": flow["actor_roles"],
                "route": flow.get("route"),
                "node_ids": [
                    node_id for node_id in flow["node_ids"] if node_id in seen
                ],
            }
            for flow in flows
        ],
        "nodes": [
            {
                key: by_id[node_id][key]
                for key in ("id", "kind", "label", "condition", "operation", "tables")
                if key in by_id[node_id]
            }
            for node_id in selected
        ],
        "edges": [
            {key: edge[key] for key in ("source", "target", "type")}
            for edge in projection["edges"]
            if edge["source"] in seen and edge["target"] in seen
        ][: caps["max_edges"]],
    }
    while len(json.dumps(reduced)) > caps["max_bytes"] and len(reduced["nodes"]) > 20:
        removed = reduced["nodes"].pop()
        seen.discard(removed["id"])
        reduced["edges"] = [
            edge
            for edge in reduced["edges"]
            if edge["source"] in seen and edge["target"] in seen
        ]
        for flow in reduced["flows"]:
            flow["node_ids"] = [
                node_id for node_id in flow["node_ids"] if node_id in seen
            ]
        reduced["complete"] = False
    return reduced


def build_request(
    projection: dict[str, Any], profile: dict[str, Any]
) -> dict[str, Any]:
    descriptor = request_descriptor()
    return {
        "model": descriptor["model"],
        "temperature": descriptor["temperature"],
        "max_tokens": descriptor["max_tokens"],
        "response_format": descriptor["response_format"],
        "messages": [
            {"role": "system", "content": descriptor["system"]},
            {
                "role": "user",
                "content": (
                    descriptor["instructions"]
                    + "\n\nGRAPH_JSON="
                    + json.dumps(reduce_projection(projection), sort_keys=True)
                    + "\n\nPROFILE_JSON="
                    + json.dumps(profile, sort_keys=True)
                ),
            },
        ],
    }


def generate(
    *,
    root: Path,
    catalogue_path: Path,
    model_path: Path,
    output: Path,
    api_key: str,
) -> dict[str, Any]:
    catalogue = load_catalog(catalogue_path)
    model = _read_mapping(model_path, label="risk model")
    projection = build_public_projection(
        catalogue,
        model,
        source_commit="local",
        repository_evidence=collect_repository_evidence(root),
    )
    request = build_request(projection, model.get("business_profile", {}))
    output_content = MistralClient(api_key).generate(request)
    parsed = parse_tree_set(json.loads(output_content.content))
    library = {
        "version": LIBRARY_VERSION,
        "note": GENERATED_NOTE,
        "trees": [
            {**tree.model_dump(), "origin": "GENERATED"} for tree in parsed.trees
        ],
    }
    validate_library(
        library,
        flow_ids={flow["id"] for flow in projection["flows"]},
        graph_node_ids={node["id"] for node in projection["nodes"]},
    )
    output.write_text(
        json.dumps(library, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return library


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--catalogue", type=Path, default=Path("bantam/workflow_catalog.json")
    )
    parser.add_argument("--model", type=Path, default=Path("report/risk-model.json"))
    parser.add_argument(
        "--output", type=Path, default=Path("report/attack-trees.generated.json")
    )
    arguments = parser.parse_args(argv)
    api_key = os.getenv("ASPIS_MISTRAL_API_KEY", "").strip()
    if not api_key:
        print("ASPIS_MISTRAL_API_KEY is not set; nothing was generated.")
        return 2
    try:
        library = generate(
            root=arguments.root,
            catalogue_path=arguments.catalogue,
            model_path=arguments.model,
            output=arguments.output,
            api_key=api_key,
        )
    except (ModelRequestError, AttackTreeLibraryError) as error:
        print(f"attack tree generation failed: {error}")
        return 1
    names = ", ".join(tree["tree_id"] for tree in library["trees"])
    print(
        f"Wrote {len(library['trees'])} validated trees to {arguments.output}: {names}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
